"""add zone/provider

Revision ID: 4b79b0f82ff5
Revises: 99f156a22f9f
Create Date: 2025-11-06 13:27:26.217547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b79b0f82ff5'
down_revision: Union[str, Sequence[str], None] = '99f156a22f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('preferred_zone', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('data_center_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'data_center_provider')
    op.drop_column('jobs', 'preferred_zone')
    # ### end Alembic commands ###
